<?php

/** @var \Marlosoft\MessengerCustomerChat\Block\Embed $block */
$helper = $block->getHelper();

?>
<div id="fb-root"></div>
<div class="fb-customerchat" <?php /* @escapeNotVerified */ echo($helper->getAttributes()); ?>></div>
<script async type="text/javascript">
  window.fbAsyncInit = function () {
    FB.init({xfbml: true, version: 'v3.2'});
  };

  (function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s);
    js.id = id;
    js.src = '<?php /* @escapeNotVerified */ echo($helper->getJsSdkUrl()); ?>';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>
